name: go2rtc 1.9.6
description: go2rtc pinned to version 1.9.6
url: https://github.com/AlexxIT/go2rtc
image: ghcr.io/alexxit/go2rtc:1.9.6
arch: [amd64, aarch64, i386, armv7]

version: 1.9.6
slug: go2rtc-1-9-6
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: ["config:rw", "media", "ssl"]
